//! Configuration and certificate management.
//!
//! Config lives in `config.toml` next to the `rose` executable when that file
//! exists, otherwise `%ProgramData%\RoSE` on Windows or `~/.config/rose` on
//! Unix (`--config-dir` overrides). Under that directory:
//! - `authorized_certs/` — client certs authorized to connect (server side)
//! - `known_hosts/` — TOFU server cert cache (client side)
//! - Client and server X.509 certificates generated by `rose keygen`

use std::path::{Path, PathBuf};
use std::sync::Arc;

use quinn::crypto::rustls::QuicClientConfig;
use rustls::SignatureScheme;
use rustls::pki_types::{CertificateDer, PrivateKeyDer, ServerName, UnixTime};
use serde::{Deserialize, Serialize};

/// Application configuration loaded from `<config_dir>/config.toml`.
///
/// All fields have sensible defaults so a missing config file is equivalent
/// to an empty one.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(default)]
pub struct RoseConfig {
    /// Require CA-signed server certificates verified against the OS trust
    /// store. When `true`, TOFU and pinned self-signed certs are rejected.
    pub require_ca_certs: bool,

    /// When `true` (the default), the server requests a client certificate and
    /// accepts only exact DER matches in `authorized_certs/`. When `false`, any
    /// client may connect. The running server rereads this on each handshake.
    pub require_client_certs: bool,

    /// Custom STUN server addresses for NAT traversal (e.g.,
    /// `["stun.example.com:3478"]`). When `None`, the built-in Google STUN
    /// servers are used.
    pub stun_servers: Option<Vec<String>>,

    /// Maximum number of concurrent sessions (active + detached). When the
    /// limit is reached, new connections are refused. `None` means no limit.
    pub max_sessions: Option<usize>,

    /// Idle timeout for detached sessions in seconds. Sessions detached
    /// longer than this are automatically pruned. `None` disables idle
    /// pruning. Defaults to 7 days (604800 seconds).
    pub session_idle_timeout_secs: Option<u64>,

    /// Retry connections the server is listening on but rejecting (for
    /// example an unauthorized client certificate). Defaults to `false`.
    pub always_retry: bool,

    /// Maximum initial connection attempts. Negative means retry forever.
    /// `0` is treated as a single attempt. Defaults to 10.
    pub retry_limit: i64,

    /// Constant delay between retries, in seconds. `None` uses the default
    /// decay schedule: 1, 2, 3, 5, 5, 5, 10, 10, 10, 30, 60, 120, ... up
    /// to one hour.
    pub retry_interval_secs: Option<u64>,

    /// When `true`, unauthorized clients get a numeric pairing code instead
    /// of a TLS reject. Off by default; enable with `rose ctl set pairing true`.
    pub pairing: bool,

    /// Pairing-code length when pairing is enabled. Minimum 2, maximum 18,
    /// default 8. Shorter codes expire faster.
    pub pairing_code_digits: u8,

    /// When `true`, each new login must present a TOTP code for the client
    /// certificate. New clients are enrolled during pairing approval.
    pub totp_required: bool,

    /// `OpenID` Connect issuer URL. With `sso_client_id`, unauthorized clients
    /// can authorize via the device flow.
    pub sso_issuer: Option<String>,

    /// OIDC client id for the device-authorization grant.
    pub sso_client_id: Option<String>,

    /// Optional OIDC client secret.
    pub sso_client_secret: Option<String>,
}

/// Seven days in seconds (default idle timeout for detached sessions).
const DEFAULT_IDLE_TIMEOUT_SECS: u64 = 7 * 24 * 60 * 60;

/// Shortest pairing code.
pub const PAIRING_MIN_DIGITS: u8 = 2;
/// Longest pairing code (`u64` remainder stays unique).
pub const PAIRING_MAX_DIGITS: u8 = 18;
/// Default pairing-code length when pairing is enabled.
pub const PAIRING_DEFAULT_DIGITS: u8 = 8;
/// Upper bound on pairing-code lifetime.
pub const PAIRING_MAX_TTL_SECS: u64 = 60 * 60;

impl Default for RoseConfig {
    fn default() -> Self {
        Self {
            require_ca_certs: false,
            require_client_certs: true,
            stun_servers: None,
            max_sessions: None,
            session_idle_timeout_secs: Some(DEFAULT_IDLE_TIMEOUT_SECS),
            always_retry: false,
            retry_limit: 10,
            retry_interval_secs: None,
            pairing: false,
            pairing_code_digits: PAIRING_DEFAULT_DIGITS,
            totp_required: false,
            sso_issuer: None,
            sso_client_id: None,
            sso_client_secret: None,
        }
    }
}

impl RoseConfig {
    /// Loads config from `<config_dir>/config.toml`, falling back to defaults
    /// if the file does not exist.
    ///
    /// # Errors
    ///
    /// Returns `ConfigError::Io` on filesystem errors or
    /// `ConfigError::ConfigParse` if the file is not valid TOML.
    pub fn load(config_dir: &Path) -> Result<Self, ConfigError> {
        let path = config_dir.join("config.toml");
        if !path.exists() {
            return Ok(Self::default());
        }
        let contents = std::fs::read_to_string(&path)?;
        toml::from_str(&contents).map_err(|e| ConfigError::ConfigParse(e.to_string()))
    }

    /// Writes `config.toml` under `config_dir`, creating the directory if needed.
    ///
    /// # Errors
    ///
    /// Returns `ConfigError::Io` on filesystem errors or
    /// `ConfigError::ConfigSerialize` if the config cannot be encoded.
    pub fn save(&self, config_dir: &Path) -> Result<(), ConfigError> {
        std::fs::create_dir_all(config_dir)?;
        let contents = toml::to_string_pretty(self)
            .map_err(|e| ConfigError::ConfigSerialize(e.to_string()))?;
        std::fs::write(config_dir.join("config.toml"), contents)?;
        Ok(())
    }

    /// Creates `authorized_certs/` and writes a default `config.toml` if missing.
    ///
    /// # Errors
    ///
    /// Returns `ConfigError::Io` or `ConfigError::ConfigSerialize`.
    pub fn ensure_dir(config_dir: &Path) -> Result<(), ConfigError> {
        std::fs::create_dir_all(config_dir.join("authorized_certs"))?;
        if !config_dir.join("config.toml").exists() {
            Self::default().save(config_dir)?;
        }
        Ok(())
    }

    /// Names of keys `rose ctl` can get or set.
    #[must_use]
    pub const fn keys() -> &'static [&'static str] {
        &[
            "require_ca_certs",
            "require_client_certs",
            "stun_servers",
            "max_sessions",
            "session_idle_timeout_secs",
            "always_retry",
            "retry_limit",
            "retry_interval_secs",
            "pairing",
            "pairing_code_digits",
            "totp_required",
            "sso_issuer",
            "sso_client_id",
            "sso_client_secret",
        ]
    }

    /// Formats one config value for `rose ctl get`.
    ///
    /// # Errors
    ///
    /// Returns `ConfigError::UnknownKey` when `key` is not a known field.
    pub fn get_key(&self, key: &str) -> Result<String, ConfigError> {
        match key {
            "require_ca_certs" => Ok(self.require_ca_certs.to_string()),
            "require_client_certs" => Ok(self.require_client_certs.to_string()),
            "stun_servers" => Ok(match &self.stun_servers {
                None => "none".to_string(),
                Some(servers) => servers.join(","),
            }),
            "max_sessions" => Ok(match self.max_sessions {
                None => "none".to_string(),
                Some(limit) => limit.to_string(),
            }),
            "session_idle_timeout_secs" => Ok(match self.session_idle_timeout_secs {
                None => "none".to_string(),
                Some(secs) => secs.to_string(),
            }),
            "always_retry" => Ok(self.always_retry.to_string()),
            "retry_limit" => Ok(self.retry_limit.to_string()),
            "retry_interval_secs" => Ok(match self.retry_interval_secs {
                None => "none".to_string(),
                Some(secs) => secs.to_string(),
            }),
            "pairing" => Ok(self.pairing.to_string()),
            "pairing_code_digits" => Ok(self.pairing_code_digits.to_string()),
            "totp_required" => Ok(self.totp_required.to_string()),
            "sso_issuer" => Ok(optional_string(&self.sso_issuer)),
            "sso_client_id" => Ok(optional_string(&self.sso_client_id)),
            "sso_client_secret" => Ok(optional_string(&self.sso_client_secret)),
            _ => Err(ConfigError::UnknownKey(key.to_string())),
        }
    }

    /// Updates one field from a `rose ctl set` value.
    ///
    /// Booleans accept `true`/`false`, `1`/`0`, and `yes`/`no`. Optional
    /// numbers and `stun_servers` accept `none` to clear. `stun_servers` is a
    /// comma-separated list.
    ///
    /// # Errors
    ///
    /// Returns `ConfigError::UnknownKey` or `ConfigError::InvalidValue`.
    pub fn set_key(&mut self, key: &str, value: &str) -> Result<(), ConfigError> {
        match key {
            "require_ca_certs" => self.require_ca_certs = parse_bool(key, value)?,
            "require_client_certs" => self.require_client_certs = parse_bool(key, value)?,
            "stun_servers" => {
                self.stun_servers = parse_optional_list(key, value)?;
            }
            "max_sessions" => self.max_sessions = parse_optional(key, value)?,
            "session_idle_timeout_secs" => {
                self.session_idle_timeout_secs = parse_optional(key, value)?;
            }
            "always_retry" => self.always_retry = parse_bool(key, value)?,
            "retry_limit" => {
                self.retry_limit = value.parse().map_err(|_| invalid_value(key, value))?;
            }
            "retry_interval_secs" => {
                self.retry_interval_secs = parse_optional(key, value)?;
            }
            "pairing" => self.pairing = parse_bool(key, value)?,
            "pairing_code_digits" => {
                let digits: u8 = value.parse().map_err(|_| invalid_value(key, value))?;
                if !(PAIRING_MIN_DIGITS..=PAIRING_MAX_DIGITS).contains(&digits) {
                    return Err(invalid_value(key, value));
                }
                self.pairing_code_digits = digits;
            }
            "totp_required" => self.totp_required = parse_bool(key, value)?,
            "sso_issuer" => self.sso_issuer = parse_optional_string(key, value)?,
            "sso_client_id" => self.sso_client_id = parse_optional_string(key, value)?,
            "sso_client_secret" => self.sso_client_secret = parse_optional_string(key, value)?,
            _ => return Err(ConfigError::UnknownKey(key.to_string())),
        }
        Ok(())
    }
}

fn invalid_value(key: &str, value: &str) -> ConfigError {
    ConfigError::InvalidValue {
        key: key.to_string(),
        value: value.to_string(),
    }
}

fn parse_bool(key: &str, value: &str) -> Result<bool, ConfigError> {
    match value.trim().to_ascii_lowercase().as_str() {
        "true" | "1" | "yes" => Ok(true),
        "false" | "0" | "no" => Ok(false),
        _ => Err(invalid_value(key, value)),
    }
}

fn parse_optional<T: std::str::FromStr>(key: &str, value: &str) -> Result<Option<T>, ConfigError> {
    let value = value.trim();
    if value.eq_ignore_ascii_case("none") || value.is_empty() {
        return Ok(None);
    }
    value
        .parse()
        .map(Some)
        .map_err(|_| invalid_value(key, value))
}

fn parse_optional_list(key: &str, value: &str) -> Result<Option<Vec<String>>, ConfigError> {
    let value = value.trim();
    if value.eq_ignore_ascii_case("none") || value.is_empty() {
        return Ok(None);
    }
    let servers: Vec<String> = value
        .split(',')
        .map(str::trim)
        .filter(|part| !part.is_empty())
        .map(ToString::to_string)
        .collect();
    if servers.is_empty() {
        return Err(invalid_value(key, value));
    }
    Ok(Some(servers))
}

fn optional_string(value: &Option<String>) -> String {
    match value {
        None => "none".to_string(),
        Some(text) => text.clone(),
    }
}

fn parse_optional_string(key: &str, value: &str) -> Result<Option<String>, ConfigError> {
    let value = value.trim();
    if value.eq_ignore_ascii_case("none") || value.is_empty() {
        return Ok(None);
    }
    if value.chars().any(char::is_control) {
        return Err(invalid_value(key, value));
    }
    Ok(Some(value.to_string()))
}

/// Returns whether the server currently requires authorized client certificates.
#[must_use]
pub fn client_certs_required(config_dir: &Path) -> bool {
    RoseConfig::load(config_dir)
        .unwrap_or_default()
        .require_client_certs
}

/// Sanitizes a hostname for safe use in filesystem paths.
///
/// Replaces any character that is not alphanumeric, `.`, `-`, or `_` with `_`,
/// preventing path traversal attacks (e.g., `../../etc/passwd`).
#[must_use]
pub fn sanitize_hostname(host: &str) -> String {
    host.chars()
        .map(|c| {
            if c.is_alphanumeric() || c == '.' || c == '-' || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect()
}

/// Errors that can occur during configuration or certificate operations.
#[derive(Debug, thiserror::Error)]
pub enum ConfigError {
    /// Certificate generation failed.
    #[error("certificate generation failed: {0}")]
    CertGen(#[from] rcgen::Error),
    /// TLS configuration error.
    #[error("TLS configuration error: {0}")]
    Tls(#[from] rustls::Error),
    /// I/O error (reading/writing cert files).
    #[error("I/O error: {0}")]
    Io(#[from] std::io::Error),
    /// Quinn crypto configuration error.
    #[error("QUIC crypto configuration error: {0}")]
    QuicCrypto(String),
    /// Config file parse error.
    #[error("config parse error: {0}")]
    ConfigParse(String),
    /// Config file serialize error.
    #[error("config serialize error: {0}")]
    ConfigSerialize(String),
    /// Unknown `rose ctl` key.
    #[error("unknown config key: {0}")]
    UnknownKey(String),
    /// Invalid `rose ctl` value.
    #[error("invalid config value for {key}: {value}")]
    InvalidValue { key: String, value: String },
    /// No pending client certificate for this pairing code.
    #[error(
        "no pending client for pairing code {0}; ask them to run rose connect once so the server can see the certificate"
    )]
    PairingUnknown(String),
    /// Pending pairing code expired.
    #[error("pairing code {0} expired; ask the client to connect again")]
    PairingExpired(String),
}

/// A generated certificate and its private key in both PEM and DER formats.
#[derive(Clone)]
pub struct CertKeyPair {
    /// PEM-encoded certificate.
    pub cert_pem: String,
    /// PEM-encoded private key.
    pub key_pem: String,
    /// DER-encoded certificate.
    pub cert_der: CertificateDer<'static>,
    /// DER-encoded private key.
    pub key_der: Vec<u8>,
}

/// Standard filesystem paths for `RoSE` configuration.
#[derive(Clone)]
pub struct RosePaths {
    /// Root config directory (e.g. `~/.config/rose/`).
    pub config_dir: PathBuf,
    /// Directory for authorized client certs (server side).
    pub authorized_certs_dir: PathBuf,
    /// Directory for pairing-code requests waiting for `rose ctl approve`.
    pub pending_certs_dir: PathBuf,
    /// Directory for cached server certs (client side, TOFU).
    pub known_hosts_dir: PathBuf,
}

impl RosePaths {
    /// Resolves the config directory used when `--config-dir` is omitted.
    ///
    /// Order: `config.toml` next to this executable, then the platform
    /// default (`%ProgramData%\RoSE` on Windows, `$HOME/.config/rose` on Unix).
    ///
    /// # Panics
    ///
    /// Panics on Unix if the `HOME` environment variable is not set.
    #[must_use]
    pub fn resolve() -> Self {
        Self::resolve_optional(None)
    }

    /// Like [`Self::resolve`], but `--config-dir` wins when set.
    #[must_use]
    pub fn resolve_optional(explicit: Option<PathBuf>) -> Self {
        Self::with_base(discover_config_dir(
            explicit.as_deref(),
            current_exe_dir().as_deref(),
            &platform_default_config_dir(),
        ))
    }

    /// Constructs paths with an explicit base directory.
    #[must_use]
    pub fn with_base(base: PathBuf) -> Self {
        Self {
            authorized_certs_dir: base.join("authorized_certs"),
            pending_certs_dir: base.join("pending_certs"),
            known_hosts_dir: base.join("known_hosts"),
            config_dir: base,
        }
    }
}

/// Picks the config directory: explicit flag, then `config.toml` beside the
/// executable, then `platform_default`.
#[must_use]
pub fn discover_config_dir(
    explicit: Option<&Path>,
    exe_dir: Option<&Path>,
    platform_default: &Path,
) -> PathBuf {
    if let Some(dir) = explicit {
        return dir.to_path_buf();
    }
    if let Some(dir) = exe_dir
        && dir.join("config.toml").is_file()
    {
        return dir.to_path_buf();
    }
    platform_default.to_path_buf()
}

fn current_exe_dir() -> Option<PathBuf> {
    std::env::current_exe()
        .ok()
        .and_then(|path| path.parent().map(Path::to_path_buf))
}

fn platform_default_config_dir() -> PathBuf {
    #[cfg(windows)]
    {
        let program_data = std::env::var_os("ProgramData")
            .map(PathBuf::from)
            .unwrap_or_else(|| PathBuf::from(r"C:\ProgramData"));
        program_data.join("RoSE")
    }
    #[cfg(not(windows))]
    {
        let home = std::env::var("HOME").expect("HOME environment variable not set");
        PathBuf::from(home).join(".config").join("rose")
    }
}

/// Generates a self-signed X.509 certificate for the given Subject Alternative Names.
///
/// # Errors
///
/// Returns `ConfigError::CertGen` if certificate generation fails.
pub fn generate_self_signed_cert(san: &[String]) -> Result<CertKeyPair, ConfigError> {
    let certified_key = rcgen::generate_simple_self_signed(san.to_vec())?;
    let cert_pem = certified_key.cert.pem();
    let key_pem = certified_key.signing_key.serialize_pem();
    let cert_der = certified_key.cert.der().clone();
    let key_der = certified_key.signing_key.serialize_der();

    Ok(CertKeyPair {
        cert_pem,
        key_pem,
        cert_der,
        key_der,
    })
}

/// Result of a TOFU (Trust On First Use) certificate check.
#[derive(Debug, PartialEq, Eq)]
pub enum TofuResult {
    /// First time connecting to this host — cert was saved.
    FirstConnection,
    /// Cached cert matches the server's cert.
    Verified,
    /// Cached cert does NOT match — possible MITM attack.
    Mismatch {
        /// Path to the cached certificate that doesn't match.
        cached_path: PathBuf,
    },
}

/// Checks a server certificate against a TOFU known-hosts directory.
///
/// - If no cached cert exists for `host`, saves `server_cert_der` and returns `FirstConnection`.
/// - If the cached cert matches, returns `Verified`.
/// - If it differs, returns `Mismatch`.
///
/// # Errors
///
/// Returns `ConfigError::Io` if filesystem operations fail.
pub fn tofu_check(
    known_hosts_dir: &Path,
    host: &str,
    server_cert_der: &[u8],
) -> Result<TofuResult, ConfigError> {
    let sanitized = sanitize_hostname(host);
    let cert_path = known_hosts_dir.join(format!("{sanitized}.crt"));

    if cert_path.exists() {
        let cached = std::fs::read(&cert_path)?;
        if cached == server_cert_der {
            Ok(TofuResult::Verified)
        } else {
            Ok(TofuResult::Mismatch {
                cached_path: cert_path,
            })
        }
    } else {
        std::fs::create_dir_all(known_hosts_dir)?;
        std::fs::write(&cert_path, server_cert_der)?;
        Ok(TofuResult::FirstConnection)
    }
}

/// Computes the SHA-256 fingerprint of a DER-encoded certificate.
///
/// Returns a colon-separated hex string (e.g., `ab:cd:ef:...`).
#[must_use]
pub fn cert_fingerprint(cert_der: &[u8]) -> String {
    let hash = ring::digest::digest(&ring::digest::SHA256, cert_der);
    hash.as_ref()
        .iter()
        .map(|b| format!("{b:02x}"))
        .collect::<Vec<_>>()
        .join(":")
}

/// Checks that a DER-encoded certificate is currently valid (not expired,
/// not yet valid). Used by both [`PinnedCertVerifier`] and
/// [`TofuFirstConnectionVerifier`] to enforce expiry on self-signed certs.
pub(crate) fn check_cert_expiry(
    cert_der: &CertificateDer<'_>,
    now: UnixTime,
) -> Result<(), rustls::Error> {
    use x509_parser::prelude::FromDer;
    let (_, cert) = x509_parser::certificate::X509Certificate::from_der(cert_der.as_ref())
        .map_err(|_| rustls::Error::InvalidCertificate(rustls::CertificateError::BadEncoding))?;
    let validity = cert.validity();
    let now_secs = now.as_secs() as i64;
    if now_secs < validity.not_before.timestamp() {
        return Err(rustls::Error::InvalidCertificate(
            rustls::CertificateError::NotValidYet,
        ));
    }
    if now_secs > validity.not_after.timestamp() {
        return Err(rustls::Error::InvalidCertificate(
            rustls::CertificateError::Expired,
        ));
    }
    Ok(())
}

/// A server certificate verifier that checks the cert matches a pinned certificate.
///
/// Unlike root-store verification, this ignores Subject Alternative Names and
/// hostname checks — the security comes from the exact cert byte match, not
/// the certificate's claimed identity. TLS handshake signatures are still
/// verified cryptographically. Certificate expiry is enforced via
/// [`check_cert_expiry`].
#[derive(Debug)]
struct PinnedCertVerifier {
    expected_cert: CertificateDer<'static>,
    provider: Arc<rustls::crypto::CryptoProvider>,
}

impl rustls::client::danger::ServerCertVerifier for PinnedCertVerifier {
    fn verify_server_cert(
        &self,
        end_entity: &CertificateDer<'_>,
        _intermediates: &[CertificateDer<'_>],
        _server_name: &ServerName<'_>,
        _ocsp_response: &[u8],
        now: UnixTime,
    ) -> Result<rustls::client::danger::ServerCertVerified, rustls::Error> {
        if end_entity.as_ref() != self.expected_cert.as_ref() {
            return Err(rustls::Error::InvalidCertificate(
                rustls::CertificateError::ApplicationVerificationFailure,
            ));
        }
        check_cert_expiry(end_entity, now)?;
        Ok(rustls::client::danger::ServerCertVerified::assertion())
    }

    fn verify_tls12_signature(
        &self,
        message: &[u8],
        cert: &CertificateDer<'_>,
        dss: &rustls::DigitallySignedStruct,
    ) -> Result<rustls::client::danger::HandshakeSignatureValid, rustls::Error> {
        rustls::crypto::verify_tls12_signature(
            message,
            cert,
            dss,
            &self.provider.signature_verification_algorithms,
        )
    }

    fn verify_tls13_signature(
        &self,
        message: &[u8],
        cert: &CertificateDer<'_>,
        dss: &rustls::DigitallySignedStruct,
    ) -> Result<rustls::client::danger::HandshakeSignatureValid, rustls::Error> {
        rustls::crypto::verify_tls13_signature(
            message,
            cert,
            dss,
            &self.provider.signature_verification_algorithms,
        )
    }

    fn supported_verify_schemes(&self) -> Vec<SignatureScheme> {
        self.provider
            .signature_verification_algorithms
            .supported_schemes()
    }
}

/// A server certificate verifier that accepts any certificate identity but
/// still cryptographically verifies TLS handshake signatures and enforces
/// certificate expiry via [`check_cert_expiry`].
///
/// Used for the TOFU first-connection flow: we don't know which cert to
/// expect, but we must verify the server actually holds the private key
/// for the cert it presents (otherwise a MITM could present an arbitrary
/// cert and the client would cache it permanently).
#[derive(Debug)]
struct TofuFirstConnectionVerifier {
    provider: Arc<rustls::crypto::CryptoProvider>,
}

impl rustls::client::danger::ServerCertVerifier for TofuFirstConnectionVerifier {
    fn verify_server_cert(
        &self,
        end_entity: &CertificateDer<'_>,
        _intermediates: &[CertificateDer<'_>],
        _server_name: &ServerName<'_>,
        _ocsp_response: &[u8],
        now: UnixTime,
    ) -> Result<rustls::client::danger::ServerCertVerified, rustls::Error> {
        check_cert_expiry(end_entity, now)?;
        Ok(rustls::client::danger::ServerCertVerified::assertion())
    }

    fn verify_tls12_signature(
        &self,
        message: &[u8],
        cert: &CertificateDer<'_>,
        dss: &rustls::DigitallySignedStruct,
    ) -> Result<rustls::client::danger::HandshakeSignatureValid, rustls::Error> {
        rustls::crypto::verify_tls12_signature(
            message,
            cert,
            dss,
            &self.provider.signature_verification_algorithms,
        )
    }

    fn verify_tls13_signature(
        &self,
        message: &[u8],
        cert: &CertificateDer<'_>,
        dss: &rustls::DigitallySignedStruct,
    ) -> Result<rustls::client::danger::HandshakeSignatureValid, rustls::Error> {
        rustls::crypto::verify_tls13_signature(
            message,
            cert,
            dss,
            &self.provider.signature_verification_algorithms,
        )
    }

    fn supported_verify_schemes(&self) -> Vec<SignatureScheme> {
        self.provider
            .signature_verification_algorithms
            .supported_schemes()
    }
}

/// Builds a quinn `ClientConfig` that verifies the server certificate against
/// the OS trust store and provides a client cert for mutual TLS.
///
/// Use this when `require_ca_certs` is `true` — the server must present a
/// CA-signed certificate (e.g., from Let's Encrypt).
///
/// # Errors
///
/// Returns `ConfigError` if the TLS configuration cannot be built.
pub fn build_platform_verified_client_config_with_cert(
    client_cert: &CertKeyPair,
) -> Result<quinn::ClientConfig, ConfigError> {
    let provider = Arc::new(rustls::crypto::ring::default_provider());
    let verifier = rustls_platform_verifier::Verifier::new(Arc::clone(&provider))
        .map_err(|e| ConfigError::QuicCrypto(format!("platform verifier: {e}")))?;
    finish_client_config(provider, Arc::new(verifier), client_cert)
}

/// Returns true if `cert_der` exactly matches a `.crt` file in `authorized_certs_dir`.
///
/// Unreadable files and names that do not end in `.crt` are skipped. A missing
/// directory or an empty directory authorizes nobody.
#[must_use]
pub fn is_authorized_client_cert(authorized_certs_dir: &Path, cert_der: &[u8]) -> bool {
    let Ok(entries) = std::fs::read_dir(authorized_certs_dir) else {
        return false;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if !path.extension().is_some_and(|ext| ext == "crt") {
            continue;
        }
        let Ok(bytes) = std::fs::read(&path) else {
            continue;
        };
        if bytes == cert_der {
            return true;
        }
    }
    false
}

/// Path of the `authorized_certs/*.crt` that matches `cert_der`.
#[must_use]
pub fn authorized_cert_path(authorized_certs_dir: &Path, cert_der: &[u8]) -> Option<PathBuf> {
    let Ok(entries) = std::fs::read_dir(authorized_certs_dir) else {
        return None;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if !path.extension().is_some_and(|ext| ext == "crt") {
            continue;
        }
        let Ok(bytes) = std::fs::read(&path) else {
            continue;
        };
        if bytes == cert_der {
            return Some(path);
        }
    }
    None
}

/// True when pairing or SSO may accept an unauthorized client at TLS.
#[must_use]
pub fn provisional_unauthorized_ok(config_dir: &Path) -> bool {
    let cfg = RoseConfig::load(config_dir).unwrap_or_default();
    cfg.pairing || cfg.sso_settings().is_some()
}

/// How long an 8-digit pairing request stays approvable, in seconds.
pub const PAIRING_TTL_SECS: u64 = 120;

const MAX_PENDING_CERTS: usize = 64;

/// Lifetime of a pairing code from its digit count.
///
/// 2 digits → 15s, 4 → 30s, 6 → 60s, 8 → 120s, doubling every two digits,
/// capped at one hour.
#[must_use]
pub const fn pairing_ttl_secs(digits: u8) -> u64 {
    let digits = if digits < PAIRING_MIN_DIGITS {
        PAIRING_MIN_DIGITS
    } else if digits > PAIRING_MAX_DIGITS {
        PAIRING_MAX_DIGITS
    } else {
        digits
    };
    let exp = ((digits - PAIRING_MIN_DIGITS) / 2) as u32;
    match 15u64.checked_shl(exp) {
        Some(ttl) if ttl > PAIRING_MAX_TTL_SECS => PAIRING_MAX_TTL_SECS,
        Some(ttl) => ttl,
        None => PAIRING_MAX_TTL_SECS,
    }
}

/// Canonicalizes a user-typed pairing code to digits only.
///
/// # Errors
///
/// Returns `ConfigError::InvalidValue` when there are fewer than two digits
/// or more than [`PAIRING_MAX_DIGITS`].
pub fn normalize_pairing_code(input: &str) -> Result<String, ConfigError> {
    let compact: String = input.chars().filter(char::is_ascii_digit).collect();
    let len = compact.len();
    if len < usize::from(PAIRING_MIN_DIGITS) || len > usize::from(PAIRING_MAX_DIGITS) {
        return Err(invalid_value("pairing_code", input));
    }
    Ok(compact)
}

/// A pairing request waiting for `rose ctl approve`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PendingClient {
    /// Canonical pairing code (digits only).
    pub code: String,
    /// Seconds since the client last presented this certificate.
    pub age_secs: u64,
}

/// Writes `cert_der` under `pending_certs/` so an operator can approve it.
///
/// Expired and excess pending files are pruned. Disk errors are logged and
/// do not prevent the handshake from being rejected.
#[must_use]
pub fn record_pending_client_cert(config_dir: &Path, cert_der: &[u8]) -> String {
    let digits =
        RoseConfig::load(config_dir).map_or(PAIRING_DEFAULT_DIGITS, |cfg| cfg.pairing_code_digits);
    record_pending_client_cert_with_digits(config_dir, cert_der, digits)
}

/// Like [`record_pending_client_cert`] with an explicit code length.
#[must_use]
pub fn record_pending_client_cert_with_digits(
    config_dir: &Path,
    cert_der: &[u8],
    digits: u8,
) -> String {
    let digits = digits.clamp(PAIRING_MIN_DIGITS, PAIRING_MAX_DIGITS);
    if let Some(existing) = pending_code_for_cert(config_dir, cert_der) {
        return existing;
    }
    let dir = config_dir.join("pending_certs");
    if let Err(error) = std::fs::create_dir_all(&dir) {
        tracing::warn!(%error, "failed to create pending_certs");
        return numeric_code_from_bytes(cert_der, digits);
    }
    let mut code = random_numeric_code(digits);
    for _ in 0..32 {
        let path = dir.join(format!("{code}.crt"));
        if !path.exists() {
            if let Err(error) = std::fs::write(&path, cert_der) {
                tracing::warn!(%error, code, "failed to record pending client certificate");
            }
            prune_pending_certs(&dir);
            return code;
        }
        code = random_numeric_code(digits);
    }
    let path = dir.join(format!("{code}.crt"));
    let _ = std::fs::write(&path, cert_der);
    prune_pending_certs(&dir);
    code
}

/// Lists non-expired pending pairing requests, newest first.
#[must_use]
pub fn list_pending_client_certs(config_dir: &Path) -> Vec<PendingClient> {
    let dir = config_dir.join("pending_certs");
    let Ok(entries) = std::fs::read_dir(&dir) else {
        return Vec::new();
    };
    let now = std::time::SystemTime::now();
    let mut pending = Vec::new();
    for entry in entries.flatten() {
        let path = entry.path();
        let Some(code) = pairing_code_from_filename(&path) else {
            continue;
        };
        let Ok(modified) = entry.metadata().and_then(|meta| meta.modified()) else {
            continue;
        };
        let Ok(age) = now.duration_since(modified) else {
            continue;
        };
        if age.as_secs() > pairing_ttl_secs(code.len() as u8) {
            continue;
        }
        pending.push(PendingClient {
            code,
            age_secs: age.as_secs(),
        });
    }
    pending.sort_by_key(|item| item.age_secs);
    pending
}

/// Moves a pending client certificate into `authorized_certs/`.
///
/// # Errors
///
/// Returns `PairingUnknown` if there is no matching pending file,
/// `PairingExpired` if it is older than [`PAIRING_TTL_SECS`], or `Io`.
pub fn approve_pending_client_cert(
    config_dir: &Path,
    authorized_certs_dir: &Path,
    code: &str,
    totp: Option<&str>,
) -> Result<PathBuf, ConfigError> {
    crate::totp::verify_operator_totp(config_dir, totp)?;
    let code = normalize_pairing_code(code)?;
    let pending = config_dir.join("pending_certs").join(format!("{code}.crt"));
    if !pending.exists() {
        return Err(ConfigError::PairingUnknown(code));
    }
    if pending_is_expired(&pending) {
        let _ = std::fs::remove_file(&pending);
        return Err(ConfigError::PairingExpired(code));
    }
    let bytes = std::fs::read(&pending)?;
    std::fs::create_dir_all(authorized_certs_dir)?;
    let dest = authorized_certs_dir.join(format!("{code}.crt"));
    std::fs::write(&dest, bytes)?;
    let _ = std::fs::remove_file(&pending);
    Ok(dest)
}

/// Deletes a pending pairing request.
///
/// # Errors
///
/// Returns `PairingUnknown` if there is no matching pending file.
pub fn deny_pending_client_cert(config_dir: &Path, code: &str) -> Result<PathBuf, ConfigError> {
    let code = normalize_pairing_code(code)?;
    let pending = config_dir.join("pending_certs").join(format!("{code}.crt"));
    if !pending.exists() {
        return Err(ConfigError::PairingUnknown(code));
    }
    std::fs::remove_file(&pending)?;
    Ok(pending)
}

fn pairing_code_from_filename(path: &Path) -> Option<String> {
    let name = path.file_name()?.to_str()?;
    let stem = name.strip_suffix(".crt")?;
    normalize_pairing_code(stem).ok()
}

fn pending_code_for_cert(config_dir: &Path, cert_der: &[u8]) -> Option<String> {
    let dir = config_dir.join("pending_certs");
    let entries = std::fs::read_dir(&dir).ok()?;
    for entry in entries.flatten() {
        let path = entry.path();
        let Some(code) = pairing_code_from_filename(&path) else {
            continue;
        };
        if pending_is_expired(&path) {
            continue;
        }
        let Ok(bytes) = std::fs::read(&path) else {
            continue;
        };
        if bytes == cert_der {
            return Some(code);
        }
    }
    None
}

/// True when `cert_der` has a non-expired pairing request.
#[must_use]
pub fn has_pending_client_cert(config_dir: &Path, cert_der: &[u8]) -> bool {
    pending_code_for_cert(config_dir, cert_der).is_some()
}

fn pending_is_expired(path: &Path) -> bool {
    let Some(code) = pairing_code_from_filename(path) else {
        return true;
    };
    let Ok(modified) = std::fs::metadata(path).and_then(|meta| meta.modified()) else {
        return true;
    };
    std::time::SystemTime::now()
        .duration_since(modified)
        .map_or(true, |age| {
            age.as_secs() > pairing_ttl_secs(code.len() as u8)
        })
}

fn random_numeric_code(digits: u8) -> String {
    let mut bytes = [0u8; 8];
    if getrandom::getrandom(&mut bytes).is_err() {
        return numeric_code_from_bytes(&bytes, digits);
    }
    numeric_code_from_bytes(&bytes, digits)
}

fn numeric_code_from_bytes(bytes: &[u8], digits: u8) -> String {
    let digits = digits.clamp(PAIRING_MIN_DIGITS, PAIRING_MAX_DIGITS);
    let mut n = 0u64;
    for byte in bytes {
        n = n.wrapping_mul(256).wrapping_add(u64::from(*byte));
    }
    let modulus = 10u64.pow(u32::from(digits));
    format!("{:0width$}", n % modulus, width = usize::from(digits))
}

fn prune_pending_certs(dir: &Path) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    let now = std::time::SystemTime::now();
    let mut keep = Vec::new();
    for entry in entries.flatten() {
        let path = entry.path();
        if pairing_code_from_filename(&path).is_none() {
            continue;
        }
        let Ok(modified) = entry.metadata().and_then(|meta| meta.modified()) else {
            let _ = std::fs::remove_file(&path);
            continue;
        };
        let age = now
            .duration_since(modified)
            .unwrap_or(std::time::Duration::MAX);
        let ttl =
            pairing_code_from_filename(&path).map_or(0, |code| pairing_ttl_secs(code.len() as u8));
        if age.as_secs() > ttl {
            let _ = std::fs::remove_file(&path);
            continue;
        }
        keep.push((age, path));
    }
    keep.sort_by_key(|(age, _)| *age);
    while keep.len() > MAX_PENDING_CERTS {
        if let Some((_, path)) = keep.pop() {
            let _ = std::fs::remove_file(path);
        }
    }
}

/// Verifies client certificates against `authorized_certs/` on each handshake.
///
/// Adding or removing a `.crt` file takes effect on the next connection without
/// rebuilding the TLS config. Authorization is an exact DER match of the
/// presented end-entity certificate.
#[derive(Debug)]
struct AuthorizedClientsVerifier {
    authorized_certs_dir: PathBuf,
    config_dir: PathBuf,
    provider: Arc<rustls::crypto::CryptoProvider>,
}

impl rustls::server::danger::ClientCertVerifier for AuthorizedClientsVerifier {
    fn offer_client_auth(&self) -> bool {
        client_certs_required(&self.config_dir)
    }

    fn client_auth_mandatory(&self) -> bool {
        client_certs_required(&self.config_dir)
    }

    fn root_hint_subjects(&self) -> &[rustls::DistinguishedName] {
        &[]
    }

    fn verify_client_cert(
        &self,
        end_entity: &CertificateDer<'_>,
        _intermediates: &[CertificateDer<'_>],
        now: UnixTime,
    ) -> Result<rustls::server::danger::ClientCertVerified, rustls::Error> {
        check_cert_expiry(end_entity, now)?;
        if !client_certs_required(&self.config_dir)
            || is_authorized_client_cert(&self.authorized_certs_dir, end_entity.as_ref())
        {
            Ok(rustls::server::danger::ClientCertVerified::assertion())
        } else if provisional_unauthorized_ok(&self.config_dir) {
            if RoseConfig::load(&self.config_dir).is_ok_and(|cfg| cfg.pairing) {
                let _ = record_pending_client_cert(&self.config_dir, end_entity.as_ref());
            }
            Ok(rustls::server::danger::ClientCertVerified::assertion())
        } else {
            Err(rustls::Error::InvalidCertificate(
                rustls::CertificateError::UnknownIssuer,
            ))
        }
    }

    fn verify_tls12_signature(
        &self,
        message: &[u8],
        cert: &CertificateDer<'_>,
        dss: &rustls::DigitallySignedStruct,
    ) -> Result<rustls::client::danger::HandshakeSignatureValid, rustls::Error> {
        rustls::crypto::verify_tls12_signature(
            message,
            cert,
            dss,
            &self.provider.signature_verification_algorithms,
        )
    }

    fn verify_tls13_signature(
        &self,
        message: &[u8],
        cert: &CertificateDer<'_>,
        dss: &rustls::DigitallySignedStruct,
    ) -> Result<rustls::client::danger::HandshakeSignatureValid, rustls::Error> {
        rustls::crypto::verify_tls13_signature(
            message,
            cert,
            dss,
            &self.provider.signature_verification_algorithms,
        )
    }

    fn supported_verify_schemes(&self) -> Vec<SignatureScheme> {
        self.provider
            .signature_verification_algorithms
            .supported_schemes()
    }
}

/// Builds a quinn `ServerConfig` that requires mutual TLS client authentication.
///
/// Client certificates are authorized by exact DER match against `.crt` files in
/// `authorized_certs_dir`. The directory is read on each handshake, so adding or
/// removing a file takes effect without restarting. An empty or missing directory
/// still produces a listening server; every client is refused until a matching
/// `.crt` is present.
///
/// # Errors
///
/// Returns `ConfigError` if TLS configuration fails.
pub fn build_mutual_tls_server_config(
    cert: &CertKeyPair,
    authorized_certs_dir: &Path,
    config_dir: &Path,
) -> Result<quinn::ServerConfig, ConfigError> {
    let provider = Arc::new(rustls::crypto::ring::default_provider());
    let require_certs = client_certs_required(config_dir);
    let has_crt = std::fs::read_dir(authorized_certs_dir).is_ok_and(|entries| {
        entries
            .flatten()
            .any(|entry| entry.path().extension().is_some_and(|ext| ext == "crt"))
    });
    if require_certs && !has_crt {
        tracing::warn!(
            directory = %authorized_certs_dir.display(),
            "no authorized client certificates yet; new connections are refused until a .crt file is added or require_client_certs is set to false"
        );
    }
    let client_verifier: Arc<dyn rustls::server::danger::ClientCertVerifier> =
        Arc::new(AuthorizedClientsVerifier {
            authorized_certs_dir: authorized_certs_dir.to_path_buf(),
            config_dir: config_dir.to_path_buf(),
            provider: Arc::clone(&provider),
        });
    let rustls_config = rustls::ServerConfig::builder_with_provider(provider)
        .with_protocol_versions(&[&rustls::version::TLS13])
        .map_err(|e| ConfigError::QuicCrypto(e.to_string()))?
        .with_client_cert_verifier(client_verifier)
        .with_single_cert(
            vec![cert.cert_der.clone()],
            PrivateKeyDer::Pkcs8(cert.key_der.clone().into()),
        )?;

    let mut server_config = quinn::ServerConfig::with_crypto(Arc::new(
        quinn::crypto::rustls::QuicServerConfig::try_from(rustls_config)
            .map_err(|e| ConfigError::QuicCrypto(e.to_string()))?,
    ));

    let mut transport = quinn::TransportConfig::default();
    transport.max_idle_timeout(Some(
        // 15s is well within the valid range for IdleTimeout.
        quinn::IdleTimeout::from(quinn::VarInt::from_u32(15_000)),
    ));
    server_config.transport_config(Arc::new(transport));

    Ok(server_config)
}

/// Builds a quinn `ClientConfig` that verifies a pinned server cert and provides
/// a client cert for mutual TLS.
///
/// Uses [`PinnedCertVerifier`] which checks exact cert byte equality, ignoring
/// SANs and hostname. This allows using real hostnames as `server_name` for SNI
/// while the security comes from the pinned cert match.
///
/// # Errors
///
/// Returns `ConfigError` if the TLS configuration cannot be built.
pub fn build_client_config_with_cert(
    server_cert_der: &CertificateDer<'static>,
    client_cert: &CertKeyPair,
) -> Result<quinn::ClientConfig, ConfigError> {
    let provider = Arc::new(rustls::crypto::ring::default_provider());
    let verifier = PinnedCertVerifier {
        expected_cert: server_cert_der.clone(),
        provider: Arc::clone(&provider),
    };
    finish_client_config(provider, Arc::new(verifier), client_cert)
}

/// Builds a quinn `ClientConfig` that accepts any server certificate and provides
/// a client cert for mutual TLS.
///
/// Used for the TOFU first-connection flow where the caller will extract the
/// server cert, prompt the user, and cache it for future verification.
///
/// # Errors
///
/// Returns `ConfigError` if the TLS configuration cannot be built.
pub fn build_tofu_client_config_with_cert(
    client_cert: &CertKeyPair,
) -> Result<quinn::ClientConfig, ConfigError> {
    let provider = Arc::new(rustls::crypto::ring::default_provider());
    let verifier = TofuFirstConnectionVerifier {
        provider: Arc::clone(&provider),
    };
    finish_client_config(provider, Arc::new(verifier), client_cert)
}

/// Shared tail for all `build_*_client_config_*` functions: builds
/// a `rustls::ClientConfig` with TLS 1.3 + mutual TLS, wraps it in
/// a `quinn::ClientConfig` with keep-alive transport.
fn finish_client_config(
    provider: Arc<rustls::crypto::CryptoProvider>,
    verifier: Arc<dyn rustls::client::danger::ServerCertVerifier>,
    client_cert: &CertKeyPair,
) -> Result<quinn::ClientConfig, ConfigError> {
    let rustls_config = rustls::ClientConfig::builder_with_provider(provider)
        .with_protocol_versions(&[&rustls::version::TLS13])
        .map_err(|e| ConfigError::QuicCrypto(e.to_string()))?
        .dangerous()
        .with_custom_certificate_verifier(verifier)
        .with_client_auth_cert(
            vec![client_cert.cert_der.clone()],
            PrivateKeyDer::Pkcs8(client_cert.key_der.clone().into()),
        )?;

    let quic_client_config = QuicClientConfig::try_from(rustls_config)
        .map_err(|e| ConfigError::QuicCrypto(e.to_string()))?;

    let mut client_config = quinn::ClientConfig::new(Arc::new(quic_client_config));

    let mut transport = quinn::TransportConfig::default();
    transport.keep_alive_interval(Some(std::time::Duration::from_secs(5)));
    client_config.transport_config(Arc::new(transport));

    Ok(client_config)
}

#[cfg(test)]
#[cfg_attr(coverage_nightly, coverage(off))]
mod tests {
    use super::*;

    #[test]
    fn mutual_tls_server_config_allows_an_empty_client_directory() {
        let dir = tempfile::tempdir().unwrap();
        let cert = generate_self_signed_cert(&["localhost".to_string()]).unwrap();
        build_mutual_tls_server_config(&cert, dir.path(), dir.path()).unwrap();
    }

    #[test]
    fn is_authorized_client_cert_matches_exact_der_files() {
        let dir = tempfile::tempdir().unwrap();
        let cert = generate_self_signed_cert(&["client".to_string()]).unwrap();
        assert!(!is_authorized_client_cert(
            dir.path(),
            cert.cert_der.as_ref()
        ));
        std::fs::write(dir.path().join("notes.txt"), cert.cert_der.as_ref()).unwrap();
        assert!(!is_authorized_client_cert(
            dir.path(),
            cert.cert_der.as_ref()
        ));
        std::fs::write(dir.path().join("client.crt"), cert.cert_der.as_ref()).unwrap();
        assert!(is_authorized_client_cert(
            dir.path(),
            cert.cert_der.as_ref()
        ));
        assert!(!is_authorized_client_cert(dir.path(), b"other"));
        std::fs::remove_file(dir.path().join("client.crt")).unwrap();
        assert!(!is_authorized_client_cert(
            dir.path(),
            cert.cert_der.as_ref()
        ));
    }

    #[cfg(unix)]
    #[test]
    fn is_authorized_client_cert_skips_unreadable_files() {
        use std::os::unix::fs::PermissionsExt;

        let dir = tempfile::tempdir().unwrap();
        let cert = generate_self_signed_cert(&["client".to_string()]).unwrap();
        let path = dir.path().join("client.crt");
        std::fs::write(&path, cert.cert_der.as_ref()).unwrap();
        std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o000)).unwrap();
        assert!(!is_authorized_client_cert(
            dir.path(),
            cert.cert_der.as_ref()
        ));
        std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o600)).unwrap();
    }

    #[tokio::test]
    async fn authorized_certs_are_honored_without_rebind() {
        let dir = tempfile::tempdir().unwrap();
        let server_cert = generate_self_signed_cert(&["localhost".to_string()]).unwrap();
        let client_cert = generate_self_signed_cert(&["localhost".to_string()]).unwrap();
        let server = crate::transport::QuicServer::bind_mutual_tls(
            "127.0.0.1:0".parse().unwrap(),
            server_cert,
            dir.path(),
            dir.path(),
        )
        .unwrap();
        let addr = server.local_addr().unwrap();
        let server_cert_der = server.server_cert_der().clone();
        let cert_path = dir.path().join("client.crt");

        let (live_tx, mut live_rx) = tokio::sync::mpsc::unbounded_channel();
        let accept = tokio::spawn(async move {
            loop {
                match server.accept().await {
                    Ok(Some(conn)) => {
                        if live_tx.send(conn).is_err() {
                            break;
                        }
                    }
                    Ok(None) => break,
                    Err(_) => continue,
                }
            }
        });

        let connect = {
            let server_cert_der = server_cert_der.clone();
            let client_cert = client_cert.clone();
            move || {
                let server_cert_der = server_cert_der.clone();
                let client_cert = client_cert.clone();
                async move {
                    let client = crate::transport::QuicClient::new().unwrap();
                    let conn = client
                        .connect_with_cert(addr, "localhost", &server_cert_der, &client_cert)
                        .await
                        .ok()?;
                    tokio::select! {
                        _ = conn.closed() => None,
                        () = tokio::time::sleep(std::time::Duration::from_millis(400)) => {
                            Some(conn)
                        }
                    }
                }
            }
        };

        assert!(
            connect().await.is_none(),
            "empty authorized_certs must reject the handshake"
        );

        std::fs::write(&cert_path, client_cert.cert_der.as_ref()).unwrap();
        let client_conn = connect()
            .await
            .expect("adding a .crt must authorize the client without restarting");
        let server_conn = live_rx.recv().await.expect("server accepted the client");

        std::fs::remove_file(&cert_path).unwrap();
        assert!(
            connect().await.is_none(),
            "removing the .crt must reject new handshakes without restarting"
        );

        tokio::time::timeout(std::time::Duration::from_secs(2), client_conn.closed())
            .await
            .expect("revoking the .crt must close the live connection");
        drop(server_conn);
        accept.abort();
    }

    #[test]
    fn pairing_ttl_scales_with_digit_count() {
        assert_eq!(pairing_ttl_secs(2), 15);
        assert_eq!(pairing_ttl_secs(3), 15);
        assert_eq!(pairing_ttl_secs(4), 30);
        assert_eq!(pairing_ttl_secs(6), 60);
        assert_eq!(pairing_ttl_secs(8), 120);
        assert_eq!(pairing_ttl_secs(8), PAIRING_TTL_SECS);
        assert_eq!(pairing_ttl_secs(18), PAIRING_MAX_TTL_SECS);
        assert_eq!(pairing_ttl_secs(1), pairing_ttl_secs(2));
    }

    #[test]
    fn pairing_code_is_digits_only_and_normalizes() {
        assert_eq!(normalize_pairing_code("12").unwrap(), "12");
        assert_eq!(normalize_pairing_code(" 44 ").unwrap(), "44");
        assert_eq!(normalize_pairing_code("12-34").unwrap(), "1234");
        assert_eq!(normalize_pairing_code("0012").unwrap(), "0012");
        assert!(normalize_pairing_code("1").is_err());
        assert!(normalize_pairing_code("abcd").is_err());
        let dir = tempfile::tempdir().unwrap();
        let cert = generate_self_signed_cert(&["pair".to_string()]).unwrap();
        let code = record_pending_client_cert_with_digits(dir.path(), cert.cert_der.as_ref(), 2);
        assert_eq!(code.len(), 2);
        assert!(code.chars().all(|c| c.is_ascii_digit()));
        assert_eq!(
            record_pending_client_cert_with_digits(dir.path(), cert.cert_der.as_ref(), 8),
            code,
            "the same pending cert keeps its original code"
        );
    }

    #[test]
    fn approve_pending_cert_authorizes_the_client() {
        let dir = tempfile::tempdir().unwrap();
        let paths = RosePaths::with_base(dir.path().to_path_buf());
        let cert = generate_self_signed_cert(&["pair".to_string()]).unwrap();
        let code = record_pending_client_cert(dir.path(), cert.cert_der.as_ref());
        assert_eq!(list_pending_client_certs(dir.path())[0].code, code);
        let dest =
            approve_pending_client_cert(dir.path(), &paths.authorized_certs_dir, &code, None)
                .unwrap();
        assert!(is_authorized_client_cert(
            &paths.authorized_certs_dir,
            cert.cert_der.as_ref()
        ));
        assert_eq!(dest.file_name().unwrap(), format!("{code}.crt").as_str());
        assert!(list_pending_client_certs(dir.path()).is_empty());
        assert!(matches!(
            approve_pending_client_cert(dir.path(), &paths.authorized_certs_dir, &code, None),
            Err(ConfigError::PairingUnknown(_))
        ));
    }

    #[test]
    fn expired_pending_cert_cannot_be_approved() {
        let dir = tempfile::tempdir().unwrap();
        let paths = RosePaths::with_base(dir.path().to_path_buf());
        let cert = generate_self_signed_cert(&["pair".to_string()]).unwrap();
        let code = record_pending_client_cert_with_digits(dir.path(), cert.cert_der.as_ref(), 2);
        let pending = dir.path().join("pending_certs").join(format!("{code}.crt"));
        let old =
            std::time::SystemTime::now() - std::time::Duration::from_secs(pairing_ttl_secs(2) + 1);
        std::fs::File::open(&pending)
            .unwrap()
            .set_modified(old)
            .unwrap();
        assert!(list_pending_client_certs(dir.path()).is_empty());
        assert!(matches!(
            approve_pending_client_cert(dir.path(), &paths.authorized_certs_dir, &code, None),
            Err(ConfigError::PairingExpired(_))
        ));
        assert!(!is_authorized_client_cert(
            &paths.authorized_certs_dir,
            cert.cert_der.as_ref()
        ));
    }

    #[test]
    fn deny_pending_cert_removes_the_request() {
        let dir = tempfile::tempdir().unwrap();
        let cert = generate_self_signed_cert(&["pair".to_string()]).unwrap();
        let code = record_pending_client_cert(dir.path(), cert.cert_der.as_ref());
        deny_pending_client_cert(dir.path(), &code).unwrap();
        assert!(list_pending_client_certs(dir.path()).is_empty());
        assert!(matches!(
            deny_pending_client_cert(dir.path(), &code),
            Err(ConfigError::PairingUnknown(_))
        ));
    }

    #[tokio::test]
    async fn pairing_approve_allows_connect_without_rebind() {
        let dir = tempfile::tempdir().unwrap();
        let paths = RosePaths::with_base(dir.path().to_path_buf());
        let server_cert = generate_self_signed_cert(&["localhost".to_string()]).unwrap();
        let client_cert = generate_self_signed_cert(&["localhost".to_string()]).unwrap();
        let server = crate::transport::QuicServer::bind_mutual_tls(
            "127.0.0.1:0".parse().unwrap(),
            server_cert,
            paths.authorized_certs_dir.as_path(),
            dir.path(),
        )
        .unwrap();
        let addr = server.local_addr().unwrap();
        let server_cert_der = server.server_cert_der().clone();
        let accept =
            tokio::spawn(async move { while let Ok(Some(_)) | Err(_) = server.accept().await {} });

        let connect = {
            let server_cert_der = server_cert_der.clone();
            let client_cert = client_cert.clone();
            move || {
                let server_cert_der = server_cert_der.clone();
                let client_cert = client_cert.clone();
                async move {
                    let client = crate::transport::QuicClient::new().unwrap();
                    let conn = client
                        .connect_with_cert(addr, "localhost", &server_cert_der, &client_cert)
                        .await
                        .ok()?;
                    tokio::select! {
                        _ = conn.closed() => None,
                        () = tokio::time::sleep(std::time::Duration::from_millis(400)) => {
                            Some(conn)
                        }
                    }
                }
            }
        };

        assert!(connect().await.is_none());
        assert!(list_pending_client_certs(dir.path()).is_empty());

        let mut cfg = RoseConfig::load(dir.path()).unwrap();
        cfg.set_key("pairing", "true").unwrap();
        cfg.set_key("pairing_code_digits", "4").unwrap();
        cfg.save(dir.path()).unwrap();

        connect()
            .await
            .expect("pairing=true must accept TLS so the client can see a code");
        let pending = list_pending_client_certs(dir.path());
        assert_eq!(pending.len(), 1);
        let code = &pending[0].code;
        assert_eq!(code.len(), 4);
        assert!(code.chars().all(|c| c.is_ascii_digit()));
        approve_pending_client_cert(dir.path(), &paths.authorized_certs_dir, code, None).unwrap();
        connect()
            .await
            .expect("approving the pairing code must authorize without restarting");
        accept.abort();
    }

    #[tokio::test]
    async fn require_client_certs_can_be_toggled_without_rebind() {
        let dir = tempfile::tempdir().unwrap();
        let server_cert = generate_self_signed_cert(&["localhost".to_string()]).unwrap();
        let client_cert = generate_self_signed_cert(&["localhost".to_string()]).unwrap();
        let server = crate::transport::QuicServer::bind_mutual_tls(
            "127.0.0.1:0".parse().unwrap(),
            server_cert,
            dir.path(),
            dir.path(),
        )
        .unwrap();
        let addr = server.local_addr().unwrap();
        let server_cert_der = server.server_cert_der().clone();

        let (live_tx, mut live_rx) = tokio::sync::mpsc::unbounded_channel();
        let accept = tokio::spawn(async move {
            loop {
                match server.accept().await {
                    Ok(Some(conn)) => {
                        if live_tx.send(conn).is_err() {
                            break;
                        }
                    }
                    Ok(None) => break,
                    Err(_) => continue,
                }
            }
        });

        let connect = {
            let server_cert_der = server_cert_der.clone();
            let client_cert = client_cert.clone();
            move || {
                let server_cert_der = server_cert_der.clone();
                let client_cert = client_cert.clone();
                async move {
                    let client = crate::transport::QuicClient::new().unwrap();
                    let conn = client
                        .connect_with_cert(addr, "localhost", &server_cert_der, &client_cert)
                        .await
                        .ok()?;
                    tokio::select! {
                        _ = conn.closed() => None,
                        () = tokio::time::sleep(std::time::Duration::from_millis(400)) => {
                            Some(conn)
                        }
                    }
                }
            }
        };

        assert!(
            connect().await.is_none(),
            "certs required by default with an empty allowlist"
        );

        let mut cfg = RoseConfig::load(dir.path()).unwrap();
        cfg.set_key("require_client_certs", "false").unwrap();
        cfg.save(dir.path()).unwrap();

        let client_conn = connect()
            .await
            .expect("require_client_certs=false must accept without a restart");
        let server_conn = live_rx.recv().await.expect("server accepted the client");

        cfg.set_key("require_client_certs", "true").unwrap();
        cfg.save(dir.path()).unwrap();
        assert!(
            connect().await.is_none(),
            "re-enabling require_client_certs must reject new handshakes"
        );

        tokio::time::timeout(std::time::Duration::from_secs(2), client_conn.closed())
            .await
            .expect("re-enabling require_client_certs must close the live connection");
        drop(server_conn);
        accept.abort();
    }

    #[test]
    fn generate_cert_roundtrip() {
        let cert =
            generate_self_signed_cert(&["localhost".to_string(), "127.0.0.1".to_string()]).unwrap();

        assert!(!cert.cert_pem.is_empty());
        assert!(!cert.key_pem.is_empty());
        assert!(!cert.cert_der.is_empty());
        assert!(!cert.key_der.is_empty());
        assert!(cert.cert_pem.contains("BEGIN CERTIFICATE"));
        assert!(cert.key_pem.contains("BEGIN PRIVATE KEY"));
    }

    #[test]
    fn paths_resolve() {
        let paths = RosePaths::resolve();
        let name = paths
            .config_dir
            .file_name()
            .unwrap()
            .to_string_lossy()
            .to_ascii_lowercase();
        assert_eq!(name, "rose");
        assert!(paths.authorized_certs_dir.ends_with("authorized_certs"));
        assert!(paths.pending_certs_dir.ends_with("pending_certs"));
        assert!(paths.known_hosts_dir.ends_with("known_hosts"));
    }

    #[test]
    fn discover_config_dir_prefers_explicit_then_sidecar_then_default() {
        let default = PathBuf::from("/var/lib/rose-default");
        let explicit = PathBuf::from("/opt/explicit-rose");
        assert_eq!(
            discover_config_dir(Some(&explicit), None, &default),
            explicit
        );

        let sidecar = tempfile::tempdir().unwrap();
        assert_eq!(
            discover_config_dir(None, Some(sidecar.path()), &default),
            default,
            "a directory without config.toml must not steal the default"
        );

        std::fs::write(
            sidecar.path().join("config.toml"),
            "require_client_certs = false\n",
        )
        .unwrap();
        assert_eq!(
            discover_config_dir(None, Some(sidecar.path()), &default),
            sidecar.path(),
            "config.toml next to the executable is the config directory"
        );
        assert_eq!(
            discover_config_dir(Some(&explicit), Some(sidecar.path()), &default),
            explicit,
            "--config-dir wins over a sidecar config.toml"
        );
    }

    #[test]
    fn platform_default_config_dir_is_os_specific() {
        let dir = platform_default_config_dir();
        #[cfg(windows)]
        {
            assert!(
                dir.ends_with("RoSE"),
                "Windows default should be %ProgramData%\\RoSE, got {}",
                dir.display()
            );
        }
        #[cfg(not(windows))]
        {
            assert!(
                dir.ends_with(".config/rose") || dir.ends_with(".config\\rose"),
                "Unix default should be $HOME/.config/rose, got {}",
                dir.display()
            );
        }
    }

    #[test]
    fn ensure_dir_writes_default_toml_once() {
        let dir = tempfile::tempdir().unwrap();
        RoseConfig::ensure_dir(dir.path()).unwrap();
        let toml = dir.path().join("config.toml");
        assert!(dir.path().join("authorized_certs").is_dir());
        assert!(toml.is_file());
        let original = std::fs::read_to_string(&toml).unwrap();
        assert!(original.contains("require_client_certs"));
        std::fs::write(&toml, "require_client_certs = false\n").unwrap();
        RoseConfig::ensure_dir(dir.path()).unwrap();
        assert_eq!(
            std::fs::read_to_string(&toml).unwrap(),
            "require_client_certs = false\n"
        );
    }

    #[test]
    fn tofu_first_connection_saves_cert() {
        let dir = std::env::temp_dir().join(format!("rose-tofu-test-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);

        let cert_data = b"fake-cert-der-data";
        let result = tofu_check(&dir, "example.com", cert_data).unwrap();
        assert_eq!(result, TofuResult::FirstConnection);

        // Cert file should exist now
        let cert_path = dir.join("example.com.crt");
        assert!(cert_path.exists());
        assert_eq!(std::fs::read(&cert_path).unwrap(), cert_data);

        std::fs::remove_dir_all(&dir).unwrap();
    }

    #[test]
    fn tofu_verified_on_matching_cert() {
        let dir = std::env::temp_dir().join(format!("rose-tofu-verify-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);

        let cert_data = b"matching-cert";
        // First connection saves it
        tofu_check(&dir, "host1", cert_data).unwrap();
        // Second connection verifies it
        let result = tofu_check(&dir, "host1", cert_data).unwrap();
        assert_eq!(result, TofuResult::Verified);

        std::fs::remove_dir_all(&dir).unwrap();
    }

    #[test]
    fn tofu_mismatch_on_changed_cert() {
        let dir = std::env::temp_dir().join(format!("rose-tofu-mismatch-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);

        let cert_v1 = b"original-cert";
        let cert_v2 = b"changed-cert";
        tofu_check(&dir, "host2", cert_v1).unwrap();
        let result = tofu_check(&dir, "host2", cert_v2).unwrap();
        assert_eq!(
            result,
            TofuResult::Mismatch {
                cached_path: dir.join("host2.crt"),
            }
        );

        std::fs::remove_dir_all(&dir).unwrap();
    }

    #[test]
    fn sanitize_hostname_normal() {
        assert_eq!(sanitize_hostname("example.com"), "example.com");
        assert_eq!(sanitize_hostname("host-1_a"), "host-1_a");
    }

    #[test]
    fn sanitize_hostname_path_traversal() {
        assert_eq!(sanitize_hostname("../../etc/passwd"), ".._.._etc_passwd");
        assert_eq!(sanitize_hostname("foo/bar"), "foo_bar");
    }

    #[test]
    fn tofu_path_traversal_is_contained() {
        let dir = std::env::temp_dir().join(format!("rose-tofu-traversal-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);

        let result = tofu_check(&dir, "../../etc/shadow", b"cert").unwrap();
        assert_eq!(result, TofuResult::FirstConnection);
        assert!(dir.join(".._.._etc_shadow.crt").exists());

        std::fs::remove_dir_all(&dir).unwrap();
    }

    #[test]
    fn paths_with_base() {
        let paths = RosePaths::with_base(PathBuf::from("/tmp/rose-test"));
        assert_eq!(paths.config_dir, PathBuf::from("/tmp/rose-test"));
        assert_eq!(
            paths.authorized_certs_dir,
            PathBuf::from("/tmp/rose-test/authorized_certs")
        );
        assert_eq!(
            paths.pending_certs_dir,
            PathBuf::from("/tmp/rose-test/pending_certs")
        );
        assert_eq!(
            paths.known_hosts_dir,
            PathBuf::from("/tmp/rose-test/known_hosts")
        );
    }

    #[test]
    fn cert_fingerprint_properties() {
        let fp = cert_fingerprint(b"test cert data");
        let parts: Vec<&str> = fp.split(':').collect();
        assert_eq!(parts.len(), 32);
        for part in &parts {
            assert_eq!(part.len(), 2);
            assert!(part.chars().all(|c| c.is_ascii_hexdigit()));
        }
        assert_eq!(cert_fingerprint(b"test cert data"), fp);
        assert_ne!(cert_fingerprint(b"cert-a"), cert_fingerprint(b"cert-b"));
    }

    #[test]
    fn build_client_config_with_cert_succeeds() {
        let server = generate_self_signed_cert(&["localhost".to_string()]).unwrap();
        let client = generate_self_signed_cert(&["localhost".to_string()]).unwrap();
        let config = build_client_config_with_cert(&server.cert_der, &client);
        assert!(config.is_ok());
    }

    #[test]
    fn build_tofu_client_config_with_cert_succeeds() {
        let client = generate_self_signed_cert(&["localhost".to_string()]).unwrap();
        let config = build_tofu_client_config_with_cert(&client);
        assert!(config.is_ok());
    }

    #[test]
    fn build_platform_verified_client_config_with_cert_succeeds() {
        let client = generate_self_signed_cert(&["localhost".to_string()]).unwrap();
        let config = build_platform_verified_client_config_with_cert(&client);
        assert!(config.is_ok());
    }

    #[test]
    fn config_defaults() {
        let cfg = RoseConfig::default();
        assert!(!cfg.require_ca_certs);
        assert!(cfg.require_client_certs);
        assert!(cfg.stun_servers.is_none());
        assert!(cfg.max_sessions.is_none());
        assert_eq!(cfg.session_idle_timeout_secs, Some(604_800));
        assert!(!cfg.always_retry);
        assert_eq!(cfg.retry_limit, 10);
        assert!(cfg.retry_interval_secs.is_none());
        assert!(!cfg.pairing);
        assert_eq!(cfg.pairing_code_digits, 8);
        assert!(!cfg.totp_required);
        assert!(cfg.sso_issuer.is_none());
    }

    #[test]
    fn config_load_missing_file_returns_default() {
        let dir = tempfile::tempdir().unwrap();
        let missing = dir.path().join("nonexistent");
        let cfg = RoseConfig::load(&missing).unwrap();
        assert_eq!(cfg, RoseConfig::default());
    }

    #[test]
    fn config_load_empty_file_returns_default() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join("config.toml"), "").unwrap();
        let cfg = RoseConfig::load(dir.path()).unwrap();
        assert_eq!(cfg, RoseConfig::default());
    }

    #[test]
    fn config_load_all_fields() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(
            dir.path().join("config.toml"),
            "require_ca_certs = true\nrequire_client_certs = false\nstun_servers = [\"stun.example.com:3478\"]\nmax_sessions = 5\nsession_idle_timeout_secs = 0\nalways_retry = true\nretry_limit = -1\nretry_interval_secs = 15\npairing = true\npairing_code_digits = 4\ntotp_required = true\nsso_issuer = \"https://idp.example\"\nsso_client_id = \"rose\"\n",
        )
        .unwrap();
        let cfg = RoseConfig::load(dir.path()).unwrap();
        assert!(cfg.require_ca_certs);
        assert!(!cfg.require_client_certs);
        assert_eq!(
            cfg.stun_servers,
            Some(vec!["stun.example.com:3478".to_string()])
        );
        assert_eq!(cfg.max_sessions, Some(5));
        assert_eq!(cfg.session_idle_timeout_secs, Some(0));
        assert!(cfg.always_retry);
        assert_eq!(cfg.retry_limit, -1);
        assert_eq!(cfg.retry_interval_secs, Some(15));
        assert!(cfg.pairing);
        assert_eq!(cfg.pairing_code_digits, 4);
        assert!(cfg.totp_required);
        assert_eq!(cfg.sso_issuer.as_deref(), Some("https://idp.example"));
        assert_eq!(cfg.sso_client_id.as_deref(), Some("rose"));
    }

    #[test]
    fn config_load_invalid_toml() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join("config.toml"), "not valid {{{{ toml").unwrap();
        let err = RoseConfig::load(dir.path()).unwrap_err();
        assert!(matches!(err, ConfigError::ConfigParse(_)));
    }

    #[test]
    fn config_roundtrip_toml() {
        let cfg = RoseConfig {
            require_ca_certs: true,
            require_client_certs: false,
            stun_servers: Some(vec![
                "stun.example.com:3478".to_string(),
                "stun2.example.com:3478".to_string(),
            ]),
            max_sessions: Some(10),
            session_idle_timeout_secs: Some(3600),
            always_retry: true,
            retry_limit: -1,
            retry_interval_secs: Some(30),
            pairing: true,
            pairing_code_digits: 6,
            totp_required: true,
            sso_issuer: Some("https://idp.example".into()),
            sso_client_id: Some("rose".into()),
            sso_client_secret: None,
        };
        let serialized = toml::to_string(&cfg).unwrap();
        let deserialized: RoseConfig = toml::from_str(&serialized).unwrap();
        assert_eq!(cfg, deserialized);
    }

    #[test]
    fn config_set_and_get_keys_persist() {
        let dir = tempfile::tempdir().unwrap();
        let mut cfg = RoseConfig::default();
        cfg.set_key("require_client_certs", "no").unwrap();
        cfg.set_key("max_sessions", "3").unwrap();
        cfg.set_key(
            "stun_servers",
            "stun.example.com:3478,stun2.example.com:3478",
        )
        .unwrap();
        cfg.set_key("retry_interval_secs", "none").unwrap();
        cfg.save(dir.path()).unwrap();
        let loaded = RoseConfig::load(dir.path()).unwrap();
        assert!(!loaded.require_client_certs);
        assert_eq!(loaded.max_sessions, Some(3));
        assert_eq!(
            loaded.stun_servers,
            Some(vec![
                "stun.example.com:3478".to_string(),
                "stun2.example.com:3478".to_string()
            ])
        );
        assert_eq!(loaded.get_key("require_client_certs").unwrap(), "false");
        assert_eq!(loaded.get_key("max_sessions").unwrap(), "3");
        assert_eq!(loaded.get_key("retry_interval_secs").unwrap(), "none");
        assert!(matches!(
            loaded.get_key("not_a_key"),
            Err(ConfigError::UnknownKey(_))
        ));
        let mut cfg = loaded;
        assert!(matches!(
            cfg.set_key("require_client_certs", "maybe"),
            Err(ConfigError::InvalidValue { .. })
        ));
        cfg.set_key("max_sessions", "none").unwrap();
        assert!(cfg.max_sessions.is_none());
    }

    fn generate_cert_with_validity(
        san: &[String],
        not_before: time::OffsetDateTime,
        not_after: time::OffsetDateTime,
    ) -> CertKeyPair {
        let mut params = rcgen::CertificateParams::new(san.to_vec()).unwrap();
        params.not_before = not_before;
        params.not_after = not_after;
        let key_pair = rcgen::KeyPair::generate().unwrap();
        let cert = params.self_signed(&key_pair).unwrap();
        CertKeyPair {
            cert_pem: cert.pem(),
            key_pem: key_pair.serialize_pem(),
            cert_der: cert.der().clone(),
            key_der: key_pair.serialize_der(),
        }
    }

    #[test]
    fn check_cert_expiry_accepts_valid_cert() {
        let cert = generate_self_signed_cert(&["localhost".to_string()]).unwrap();
        let result = check_cert_expiry(&cert.cert_der, UnixTime::now());
        assert!(result.is_ok());
    }

    #[test]
    fn check_cert_expiry_rejects_expired_cert() {
        let now = time::OffsetDateTime::now_utc();
        let expired = generate_cert_with_validity(
            &["localhost".to_string()],
            now - time::Duration::days(730),
            now - time::Duration::days(365),
        );
        let result = check_cert_expiry(&expired.cert_der, UnixTime::now());
        assert!(result.is_err());
    }

    #[test]
    fn check_cert_expiry_rejects_not_yet_valid_cert() {
        let now = time::OffsetDateTime::now_utc();
        let future = generate_cert_with_validity(
            &["localhost".to_string()],
            now + time::Duration::days(365),
            now + time::Duration::days(730),
        );
        let result = check_cert_expiry(&future.cert_der, UnixTime::now());
        assert!(result.is_err());
    }

    #[test]
    fn check_cert_expiry_bad_encoding() {
        let bad_der = CertificateDer::from(vec![0xFF, 0xFE, 0xFD]);
        let result = check_cert_expiry(&bad_der, UnixTime::now());
        assert!(result.is_err());
    }
}
